---
name: release cluster image
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        env:
          BASE: 21.0.2
        run: |
          TS=$(date +%s)
          VERSION=$BASE.$TS
          echo $VERSION
          echo "VERSION_NUMBER=$VERSION" >> $GITHUB_ENV
      - name: Set ssh keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.ADMIN_PORTAL_SSH_KEY }}
            ${{ secrets.IDP_WIZARD_SSH_KEY }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: adopt
      - name: Build with Maven
        run: cd cluster/ && ./build-libs.sh && cp ../conf/cache-ispn-jdbc-ping.xml . &&
          cd ../
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
